"""initial schema

Revision ID: 2e26f81c9372
Revises: 
Create Date: 2026-03-04 13:20:35.632620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e26f81c9372'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('last_model_id', sa.String(length=100), nullable=True),
    sa.Column('last_provider', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversations_updated', 'conversations', ['updated_at'], unique=False, postgresql_ops={'updated_at': 'DESC'})
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', 'tool_call', 'tool_result', 'summary', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('model_id', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('reasoning_level', sa.String(length=20), nullable=True),
    sa.Column('tool_call_id', sa.String(length=100), nullable=True),
    sa.Column('tool_name', sa.String(length=50), nullable=True),
    sa.Column('tool_arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_result_call_id', sa.String(length=100), nullable=True),
    sa.Column('tool_result_name', sa.String(length=50), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_conversation', 'messages', ['conversation_id', 'sequence'], unique=False)
    op.create_table('rolling_summaries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('summarized_message_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('tokens_before', sa.Integer(), nullable=False),
    sa.Column('tokens_after', sa.Integer(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_summaries_conversation', 'rolling_summaries', ['conversation_id', 'created_at'], unique=False)
    op.create_table('visibility_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tokens_openai', sa.Integer(), nullable=True),
    sa.Column('tokens_anthropic', sa.Integer(), nullable=True),
    sa.Column('tokens_openrouter', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('context_window_size', sa.Integer(), nullable=True),
    sa.Column('active_token_count', sa.Integer(), nullable=True),
    sa.Column('reasoning_content', sa.Text(), nullable=True),
    sa.Column('summary_event', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visibility_records')
    op.drop_index('idx_summaries_conversation', table_name='rolling_summaries')
    op.drop_table('rolling_summaries')
    op.drop_index('idx_messages_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_conversations_updated', table_name='conversations', postgresql_ops={'updated_at': 'DESC'})
    op.drop_table('conversations')
    # ### end Alembic commands ###
